version: '3'
services:
  nginx: 
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443

  monolith:
    build: ./Monolith
    container_name: monolith
    ports:
      - "8080:8080"

  microservice-order:
    build: ./Microservice-Order
    container_name: microservice-order
    ports:
      - "8081:8081"